name: Deploy on merge of pull request
on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manually Trigger Workflow'
        required: true
        type: boolean
        default: true
jobs:
  deploy:
    if: github.event.pull_request.merged == true || inputs.manual_run == true
    runs-on: ubuntu-latest
    env: 
      WG_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      WG_PUBLIC_KEY: ${{ secrets.WIREGUARD_PUBLIC_KEY }}
      WG_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}      
      WG_CONF_FILE: '${{ github.workspace }}/../wg.conf'
      SSH_HOST: ${{ secrets.SSH_HOST }}      
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      SSH_PRIVATE_KEY_FILE: '${{ github.workspace }}/../sshpk.key'
    steps:
    - name: Configure Wireguard    
      run: |
        sudo apt install wireguard
        cat > wg.conf << EOT
        [Interface]
        PrivateKey=$WG_PRIVATE_KEY
        Address=10.189.152.219/32
        MTU=1412
        [Peer]
        PublicKey=$WG_PUBLIC_KEY
        Endpoint=$WG_ENDPOINT
        AllowedIPs=192.168.169.0/24
        EOT
        mv wg.conf $WG_CONF_FILE
    - name: Configure SSH     
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > $SSH_PRIVATE_KEY_FILE        
        sudo chmod 600 $SSH_PRIVATE_KEY_FILE
      #echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts        
    - name: Check Configurations Exist
      id: check_configs_exist
      run: |
        exist='false'
        ls $WG_CONF_FILE $SSH_PRIVATE_KEY_FILE && echo 'true' > $exist
        echo "Configurations Exist: $exist"
    - name: Wireguard Connect
      id: wireguard_connect
      if: steps.check_configs_exist.outputs.exist == 'true'
      run: |
        connected='false'
        sudo wg-quick up $WG_CONF_FILE && echo 'true' > $connected
        echo "Wireguard Connected: $connected"
    - name: SSH and Deploy
      if: steps.wireguard_connect.outputs.connected == 'true'    
      run: |
        ssh -i $SSH_PRIVATE_KEY_FILE "pyusr@$SSH_HOST"
        echo whoami
    - name: Terminate Wireguard
      if:  steps.wireguard_connect.outputs.connected == 'true'       
      run: |
        sudo wg-quick down $WG_CONF_FILE
