name: Deploy on merge of pull request
on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manually Trigger Workflow'
        required: true
        type: boolean
        default: true
jobs:
  deploy:
    if: github.event.pull_request.merged == true || inputs.manual_run == true
    runs-on: ubuntu-latest
    env: 
      WG_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      WG_PUBLIC_KEY: ${{ secrets.WIREGUARD_PUBLIC_KEY }}
      WG_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
      WG_CMD: 'wg'
      WG_CONF_FILE: '/etc/wireguard/wg.conf'
      SSH_HOST: ${{ secrets.SSH_HOST }}      
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      SSH_PRIVATE_KEY_FILE: 'sshpk.key'
    steps:
    - name: Configure Wireguard    
      run: |
        sudo apt install wireguard
        cat > wg.tmp << EOT
        [Interface]
        PrivateKey=$WG_PRIVATE_KEY
        Address=10.189.152.219/32
        MTU=1412
        [Peer]
        PublicKey=$WG_PUBLIC_KEY
        Endpoint=$WG_ENDPOINT
        AllowedIPs=192.168.169.0/24
        EOT
        sudo mv wg.tmp $WG_CONF_FILE   
    - name: Configure SSH     
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > $HOME/$SSH_PRIVATE_KEY_FILE     
        sudo chmod 600 $HOME/$SSH_PRIVATE_KEY_FILE      
      #echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts        
    - name: Verify Configurations
      id: verify_cfgs
      run: |
        echo "cfgs_exist=false" >> $GITHUB_OUTPUT
        sudo ls $WG_CONF_FILE $HOME/$SSH_PRIVATE_KEY_FILE && echo "cfgs_exist=true" >> $GITHUB_OUTPUT
    - name: Wireguard Connect
      id: wg_connect
      if: steps.verify_cfgs.outputs.cfgs_exist == 'true'    
      run: |
        echo "wg_connected=false" >> $GITHUB_OUTPUT        
        sudo wg-quick up $WG_CMD && echo "wg_connected=true" >> $GITHUB_OUTPUT 
    - name: SSH and Deploy
      if: steps.wg_connect.outputs.wg_connected == 'true'    
      run: |
        ssh -i $HOME/$SSH_PRIVATE_KEY_FILE "pyusr@$SSH_HOST"
        echo whoami
    - name: Disconnect Wireguard
      if: always() && steps.wg_connect.outputs.wg_connected == 'true' 
      run: |
        sudo wg-quick down $WG_CMD
