name: Deploy on merge of pull request
on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Manually Trigger Workflow'
        required: true
        type: boolean
        default: true
jobs:
  deploy:
    if: github.event.pull_request.merged == true || inputs.manual_run == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
    # Runs a single command using the runners shell
    - name: Prepare Wireguard
      env: 
        privatekey: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
        publickey: ${{ secrets.WIREGUARD_PUBLIC_KEY }}
        endpoint: 'dj46kqhvz4e.d.firewalla.org:51820'      
      run: |
        sudo apt install wireguard
        cat > wg.conf << EOT
        [Interface]
        PrivateKey = $privatekey
        Address=10.189.152.219/32
        MTU=1412
        [Peer]
        PublicKey=$publickey
        Endpoint=$endpoint
        AllowedIPs=192.168.169.0/24
        EOT
        sudo mv wg.conf /etc/wireguard
    #- name: Prepare SSH
      #run: |
      #  mkdir ~/.ssh/
      #  echo "${{ secrets.PCU_SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
      #  chmod 600 ~/.ssh/id_rsa
    - name: Trigger Deploy Script
      run: |
        sudo wg-quick up wg || exit 1        
        echo 'deploy script triggered
        sudo wg-quick down wg || exit 1 
